### ISSUE TITLE
Database example

### ISSUE THREAD

**Issue by singlis** [dotnet/machinelearning-samples#143]
### Purpose
There are requests for ML.Net to support  database integration to retrieve data. While we do not have database support, we do provide a way to create an IDataView from an IEnumerable, which provides an open-ended way to integrate data into an ML.Net pipeline. 

Therefore I am proposing that we provide an example of how to integrate a database as a datasource into an ML.Net pipeline using ML.Net's interface to create an IDataView from an IEnumerable. A working example would give users a starting point for their own integration. Having an example will allow us to understand the performance and limitations with using a database as a datasource.

### Entity Framework
Rather than provide a database specific implementation (like ODBC or SQL), this example will use the Entity Framework. The Entity Framework would cover a number of databases and is cross plat as it is supported in .net core. This also provides a common framework that .net developers will most likely be familiar with.

Entity Framework will also give configuration options that we can experiment with to determine what provides the best performance when using ML.Net. An example of this is eager loading vs lazy loading. 

More information about the Entity Framework can be found here:
https://docs.microsoft.com/en-us/ef/

### References
Here are the issues from ML.Net requesting/asking about database support:
https://github.com/dotnet/machinelearning/issues/1130
https://github.com/dotnet/machinelearning/issues/107
https://github.com/dotnet/machinelearning/issues/96

**Comment by asthana86** [comment]
@divega any chance you can help with this one :)?

**Comment by CESARDELATORRE** [comment]
@singlis - Agree 100%. Since you are precisely working on the ML.NET DataView loader based on Entity Framework so, as soon as it is implemented we'll publish a related sample. ok? 👍 
We'll keep this issue open until we implement such a sample or upgrade any of our samples.
Probably, the end-to-end sample "eShopDashboard Sales Forecast" has in fact all its data in a SQL database, so instead of exporting to Dataset files we could directly access to the SQL database.

**Comment by divega** [comment]
Here are a couple of things to consider for the example:

- EF Core can evaluate expressions in a LINQ query that are not translatable to SQL on the client, even in a filter predicate, which can lead to more data being transferred than expected. If the example includes using a subset of the data on a table, we should make sure we avoid this. Thd docs at https://docs.microsoft.com/ef/core/querying/client-eval explain how to control the behavior now, although we are making changes in this area in 3.0. 

- When you read data with no intention to tracking changes and saving them back to the database, you should consider using “non-tracking” queries to avoid unnecessary overhead. More details at https://docs.microsoft.com/ef/core/querying/tracking.

- In theory, non-tracking queries should handle data set that don't fit in memory, but because of some decisions we made (see the note in the docs that talks about identity resolution and weak references) it may fall short. 

- EF Core using multiple queries when eager loading collections (i.e one-to-many relationships) using the Include method. If the database connection does not support multiple active resultsets (MARS), EF Core automatically switches behavior to buffer the results of some of the queries. This can also hinder the ability to work with large data sets. If we hit this, there are some workarounds, like writing the query so that relationships are traversed in the opposite (many-to-one) direction.

**Comment by divega** [comment]
Another part of a discussion we had offline with @singlis that seems worth capturing here:

> Ordering is important when loading data from a datasource as the order needs to be consistent each time we load data. I know with dbs, the result of a query can come in any order unless the query contains a SORT of some kind. Does EF have anything regarding a consistent order?

My recommendation for this would be to explicitly request an order using ORDER BY.
 
If you don’t specify a sort order, the database will use some order determined by the query plan, usually derived from the physical order in which rows are stored in either the table or in some index. I wouldn’t expect the order of the results to be different every time you execute a query, unless an index was added or removed, or the data changed enough that the query optimizer picks a different access plan. But of course if the data really changed between runs, the fact that the order changed probably won’t matter.

**Comment by singlis** [comment]
@divega - Thank you for input/feedback!
@DevLob-zz  - Thanks for bringing this up. Where is this code? Has it changed or has the function renamed? I would like to take a look.

**Comment by singlis** [comment]
Closing as this is checked into #405
