### ISSUE TITLE
Path for Model Load and Save do not work out of the box on Mac 

### ISSUE THREAD

**Issue by nishanil** [dotnet/machinelearning-samples#174]
I was testing Github Labeler and Recommendation samples on a Mac. The file load and save path don' work out of the box. The relative path is incorrect on macOS/Linux. 
This may be applicable to all samples in the repo.

**Comment by asthana86** [comment]
@nishanil can you submit a PR to fix this particular issue.

**Comment by sebhofer** [comment]
I noticed the same issue. The question is: Relative to which directory should we set the paths? Right now this seems completely inconsistent to me...

**Comment by CESARDELATORRE** [comment]
Adding @prathyusha12345 - I just saw the issue.

Since we don't want to copy the datasets as part of the project, as a resource file, because the datasets can be huge, then...

Current relative paths are relative to the execution path when running the app in Visual Studio which is under the 'bin\Debug\netcoreapp2.1' folder, for instance

For instance:
`BinaryClassification_SentimentAnalysis\SentimentAnalysis\SentimentAnalysisConsoleApp\bin\Debug\netcoreapp2.1`

But if you run the sample with dotnet run, then the relative path is related to the root project folder, here:

`BinaryClassification_SentimentAnalysis\SentimentAnalysis\SentimentAnalysisConsoleApp`

Since the dataset files are here:

BinaryClassification_SentimentAnalysis\SentimentAnalysis\Data

In one case (Visual Studio execution) it'd be:
"../../../../Data"

The other case (CLI execution with dotnet run) it'd be:
"../Data"

We'll need to detect the app's execution context and use a different relative path depending on where it is.. 

Any other idea for this different behavior depending if using the CLI or Visual Studio?

**Comment by CESARDELATORRE** [comment]
This is fixed with this [commit](https://github.com/dotnet/machinelearning-samples/commit/827a71480a16498ac4857851edb27288ef36544a) I made for the "Sentiment Analysis" sample.
@prathyusha12345 will apply the same changes to the rest of the projects.

The issue was what I explained in the above comment.

Closing the issue, ok?

**Comment by prathyusha12345** [comment]
I created the below PR to fix this issue in all samples 
https://github.com/dotnet/machinelearning-samples/pull/275.

**Comment by prathyusha12345** [comment]
@CESARDELATORRE Thanks Cesar for reviewing and merging PR https://github.com/dotnet/machinelearning-samples/pull/275 into master

**Comment by CESARDELATORRE** [comment]
There was an issue in the PR I just fixed:
https://github.com/dotnet/machinelearning-samples/commit/e1f6c60b22c5b4b38d06250c384de53f84aa1016

**Comment by prathyusha12345** [comment]
@CESARDELATORRE  Created PR  https://github.com/dotnet/machinelearning-samples/pull/277 to remove **+** symbol in path.combine as it is not required
