### ISSUE TITLE
StopWordRemover in conjunction with FeaturizeText

### ISSUE THREAD

**Issue by lhchew** [dotnet/machinelearning-samples#176]
Hi

Looking through the text related samples (such as SentimentAnalysis), I observed that non has used stop word remover to preprocess the text before transforming and training.

May I request for samples on implementing stop word remover for text analysis?

**Comment by asthana86** [comment]
Will do, makes sense. @CESARDELATORRE

**Comment by asthana86** [comment]
@glebuk

**Comment by TomFinley** [comment]
Hi sorry for the delay in response.

Anyway, if we use the `Microsoft.ML.Transforms.Text` namespace, and we already have an `MLContext ctx` object lying around, which I assume we do, we can do `new StopWordsRemovingEstimator(ctx, "InputName", "OutputName", stopwords = ...)`, where `stopwords` is the array of tokens to remove. Intellisense might be clear. This appears to work over pre-tokenized text, that is, if you had the text `Hansel and Gretel`, you would first need to turn that scalar text into a vector of text (as via the `WordTokenizingEstimator` for example) to make it the vector `["Hansel", "and", "Gretel"]` before a stopword removal with `and` in the stopwords list would remove it.

We [might enhance this in the future](https://github.com/dotnet/machinelearning/issues/1996), since this particular transformer doesn't seem like it's seen as much love and attention as some of our others. Perhaps the original authors thought most people might be using the broader text featurizing estimator directly, I don't know.

**Comment by lhchew** [comment]
Thanks @TomFinley.  Got a sample working with your inputs.

**Comment by asthana86** [comment]
Closing this issue.
