### ISSUE TITLE
Schema mismatch for input column 'Features'

### ISSUE THREAD

**Issue by Symbai** [dotnet/machinelearning-samples#198]
Hi, I've tried following the fraud detection example but with different input values.

```
//bool, integer, integer, integer
new TextLoader.Column("Label", DataKind.BL, 0),
new TextLoader.Column("V1", DataKind.I4, 1 ),
new TextLoader.Column("V2", DataKind.I4, 2 ),
new TextLoader.Column("V3", DataKind.I4, 3 ),
```

I've changed everything in the example according my input values but when I run it, I got an exception:

```
//at TrainFastTreeAndSaveModels(), line: var model = pipeline.Fit(_trainData);
Schema mismatch for input column 'Features': expected vector or scalar of R4 or R8, got Vector<I4>
Arg_ParamName_Name
```

and it's not clear to me what's wrong. Do the input values need to have at least one float / double value at all? What line do I need to change according to my input values?

**Comment by CESARDELATORRE** [comment]
@Symbai - Can you show your code? - I think it might be related to the fact that the column concatenator, as I think the method is explicit about, in the first place requires the arguments to be all the same type. If they’re the same type, the concatenation into a vector will work – if they’re not, it won’t.

Take into account that pipeline's operations don't happen until you run "Fit()" (it has lazy execution) so it can be related to any operation in your pipeline, like what I think related to a column concatenator.

But I'm just guessing, since you are not providing your modified code but just the error, though. 👍

**Comment by glebuk** [comment]
@Symbai, 
Most of our algorithms expect floating point values as input.  You need to either read your input as floats (DataKind.R4 or DataKind.R8) or convert ints to floats later in the pipeline

**Comment by Symbai** [comment]
@glebuk: Thanks, changing everything to float obviously works but it's not what I've expected. Are there any plans to support other input values rather than float / double? Or are there any other algorithms I can use for integer only values? I'm asking because the DataKind enum has more than just float and double and it's a little bit unclear to beginners why integer only wouldn't work etc. From just looking at the sample without knowing what every method does under the hood I mean.

**Comment by CESARDELATORRE** [comment]
@Symbai - I agree with your feedback. Having to explicitly convert input variables data types to float / double is "another step" that might not be a clear requirement and in any case this is an opportunity to improve the API. 

I just created a related issue at the ML.NET repo, here:
https://github.com/dotnet/machinelearning/issues/2127

I'm closing this issue since it is related to the ML.NET API rather than the ML.NET samples, ok?

Thanks for your feedback! 👍
