### ISSUE TITLE
DeepLearning_ImageClassification_TensorFlow 0.9

### ISSUE THREAD

**Issue by DevLob-zz** [dotnet/machinelearning-samples#201]
The Example DeepLearning_ImageClassification_TensorFlow
not completely updated to 0.9 which is throw an error , as it depend on 0.8 methods which was removed

**Comment by CESARDELATORRE** [comment]
Can you provide further info about the errors you are experiencing?
This sample:
 
https://github.com/dotnet/machinelearning-samples/tree/master/samples/csharp/getting-started/DeepLearning_ImageClassification_TensorFlow

 is working for me properly on 0.9, as you can see in the screenshot below:

![image](https://user-images.githubusercontent.com/1712635/51134800-60c93d80-17ed-11e9-9a99-1b5a50c6e3b6.png)

**Comment by DevLob-zz** [comment]
for example

using Microsoft.ML.Runtime.Data; 

it throw an error that this is not found

**Comment by DevLob-zz** [comment]
https://github.com/dotnet/machinelearning-samples/blob/master/samples/csharp/getting-started/DeepLearning_ImageClassification_TensorFlow/ImageClassification/ModelScorer/ModelScorerCustom.cs

check this file please

**Comment by CESARDELATORRE** [comment]
You're right, that file was in the folder but not used in the project, that's why the sample was working.
I just deleted that file in this commit: https://github.com/dotnet/machinelearning-samples/commit/f64bb579cd10fdf8f4c4583620e53e03573970c6

ModelScorerCustom was not being used, instead, the TFModelScorer class:  https://github.com/dotnet/machinelearning-samples/blob/master/samples/csharp/getting-started/DeepLearning_ImageClassification_TensorFlow/ImageClassification/ModelScorer/TFModelScorer.cs was being use.

Closing the issue.

Thanks for catching this up! 👍
