### ISSUE TITLE
how to train multi-label  and get multi-class result  for GitHubLabeler

### ISSUE THREAD

**Issue by debin168** [dotnet/machinelearning-samples#212]
for example ,    issues  was multi-lables( memory-problrem, net-problem....)  ,when i input some issue ,the prediction is multi-label like ( memory-problrem, net-problem..)
someone give me suggestion?

**Comment by CESARDELATORRE** [comment]
It is currently not possible or straightforward to do, but we'll add this feature to the backlog.
See related issue:
https://github.com/dotnet/machinelearning/issues/2233

**Comment by CESARDELATORRE** [comment]
Good news, this is going to be possible pretty soon. 👍 
See related PR in ML.NET repo:
https://github.com/dotnet/machinelearning/pull/2250

**Comment by CESARDELATORRE** [comment]
This issue can be closed since there's a way to do it in v0.10.
However, I created the related issue below about simplifying the returned prediction info. Dealing with VBuffer and other internal classes doesn't seem an easy way to go and could probably be simplified in the future:  
https://github.com/dotnet/machinelearning/issues/2278

**Comment by debin168** [comment]
thank you for u work, it great
