### ISSUE TITLE
Is multiple train folders possible?

### ISSUE THREAD

**Issue by bakbuz** [dotnet/machinelearning-samples#219]
**code:**
```
var pipeline = mlContext.Transforms.Conversion.MapValueToKey("Label", "LabelTokey")
    .Append(mlContext.Transforms.LoadImages(imagesFolders[0], ("ImagePath", "ImageReal")))
    .Append(mlContext.Transforms.LoadImages(imagesFolders[1], ("ImagePath", "ImageReal")))
```

**tsv file:**
```
data-1\\broccoli.jpg	broccoli
data-1\\pizza.jpg	pizza
data-1\\pizza2.jpg	pizza
data-2\\teddy2.jpg	teddy
data-2\\teddy3.jpg	teddy
data-2\\teddy4.jpg	teddy
data-2\\toaster.jpg	toaster
data-2\\toaster2.png	toaster
```

**Comment by CESARDELATORRE** [comment]
Have you tried that? Do you get any exception/error?

If it is an API limitation related to TensorFlow, it'd be better to submit the issue into the ML.NET issues, here:
https://github.com/dotnet/machinelearning/issues 

Closing the issue here since it is not specifically related to the sample but probably related to the API capabilities. ok?

Thanks! 👍
