### ISSUE TITLE
Use ML.NET API in F# samples directly instead of using ModelBuilder helper module

### ISSUE THREAD

**Issue by mariuszwojcik** [dotnet/machinelearning-samples#230]
We want developers to directly learn the ML.NET API. If using these helper classes (ModelBuilder module), a developer might not clearly see how the ML.NET API is shaped.. This is specially important for the pipeline-chain API.

**Comment by charlesroddie** [comment]
Can you expand on this by posting usage using the helper classes and direct usage please?

**Comment by CESARDELATORRE** [comment]
We mean that a few months ago we were using a helper class in the samples named "ModelBuilder" so we were re-using part of the code across samples. If you want to take a look to that you can see older code in the ML. NET samples repo from around late November.

But we removed it because then when reviewing a sample you kind of learn how to use that helper class instead of the ML.NET API.
We're getting rid of that helper class for the F# samples, as well, so the samples directly use the ML.NET API.

**Comment by kevmal** [comment]
ModelBuilder module has been removed

**Comment by prathyusha12345** [comment]
As the helper class ModelBuilder is been removed I am closing the issue. Please reopen if you face any issue. thanks 👍
