### ISSUE TITLE
DeepLearning_TensorFlowEstimator  with 8bit grayscale image

### ISSUE THREAD

**Issue by rantri** [dotnet/machinelearning-samples#262]
I tried use DeepLearning_TensorFlowEstimator sample with 8 bit 1 channel grayscale images.  but the  Inception model except 24bpp color images with 3 channels.

How can I change the input to the model?

**Comment by CESARDELATORRE** [comment]
If you mean the input of the TF Inception v3 model, I'm not aware that you can change the kind of images the model expects. You probably need to modify the images so the model can process them.

In any case, here you have some interesting info about the Inception v3 TensorFLow model:
https://arxiv.org/abs/1512.00567
https://pseudoprofound.wordpress.com/2016/08/28/notes-on-the-tensorflow-implementation-of-inception-v3/

I'm closing this issue since it is not initially related to ML.NET but the specific TF Inception V3 model.
