### ISSUE TITLE
Add VB code examples

### ISSUE THREAD

**Issue by Nukepayload2** [dotnet/machinelearning-samples#27]
I want to help VB developers add the "machine learning" capability to their programs. So, I'll translate existing C# .NET Core console examples into VB.

**Comment by CESARDELATORRE** [comment]
Thanks a lot! - That would be awesome! 👍

**Comment by CESARDELATORRE** [comment]
@Nukepayload2 - For now, since there will be many API changes until we release v1.0, we've decided not to add VBs samples to the official ML.NET samples repo. However, we encourage you to publish your VB examples in your own repo in GitHub and we'll point to it from the ML.NET samples home page and ML.NET documentation so folks interested on VB samples can review it, ok? - Please, if you do, answer here so I take the URL and point to it.
Thanks! 👍

**Comment by Nukepayload2** [comment]
@CESARDELATORRE 
Ok, I'll close PR #28 and keep updating https://github.com/nukepayload2/machinelearning-samples .

**Comment by CESARDELATORRE** [comment]
Closing this issue.
