### ISSUE TITLE
LogisticRegression example using MNIST 

### ISSUE THREAD

**Issue by matnatx** [dotnet/machinelearning-samples#327]
I am trying to change MNIST example that uses the StochasticDualCoordinateAscent to use LogisticRegression instead but get the following exception thrown:

Schema mismatch for label column '': expected Key<U4>, got R4
Parameter name: labelCol

Does anyone know what this means and  how I can fix this?

I only changed:

`var trainer = mLContext.MulticlassClassification.Trainers.StochasticDualCoordinateAscent(labelColumnName: "Number", featureColumnName: DefaultColumnNames.Features);`

To:

` var trainer = mLContext.MulticlassClassification.Trainers.LogisticRegression(labelColumnName: "Number", featureColumnName: DefaultColumnNames.Features);`

Thanks!

**Comment by prathyusha12345** [comment]
@matnatx  The issue is we need to convert/map **label column** "**Number**" to a key using MapValueToKey() method during transformation so that the values of **label column "Number"**  are converted into **Numerical values** and stored in key.  (refer to this Microsoft documentation to know details of this API [here](https://docs.microsoft.com/en-us/dotnet/api/microsoft.ml.conversionsextensionscatalog.mapvaluetokey?view=ml-dotnet#Microsoft_ML_ConversionsExtensionsCatalog_MapValueToKey_Microsoft_ML_TransformsCatalog_ConversionTransforms_System_String_System_String_System_Int32_Microsoft_ML_Transforms_ValueToKeyMappingEstimator_SortOrder__)

```
Ex:  var dataProcessPipeline = mLContext.Transforms.Concatenate(DefaultColumnNames.Features, nameof(InputData.PixelValues)).AppendCacheCheckpoint(mLContext)
                    .Append(mLContext.Transforms.Conversion.MapValueToKey(outputColumnName: "keyName", inputColumnName: "Number"));
```
we need to use the **name of key** as  LabelColumnName in the training algorithm. 

`var trainer = mLContext.MulticlassClassification.Trainers.LogisticRegression(labelColumnName: "keyName", featureColumnName: DefaultColumnNames.Features);`

After appending the trainer to pipeLine you can convert back the key to label column.

` var trainingPipeline = dataProcessPipeline.Append(trainer).Append(mLContext.Transforms.Conversion.MapKeyToValue("keyName")); `

In SDCA trainer the mapping is done automatically. But for all other MultiClassClassification trainers we need to do explicit mapping of label.

For more details please see the issues https://github.com/dotnet/machinelearning/issues/2656, https://github.com/dotnet/machinelearning/issues/2628, https://github.com/dotnet/machinelearning/issues/3060 related to this.

Please try the above code and Let me know if you still face any issue, ok?

Adding @CESARDELATORRE  for reference.

**Comment by matnatx** [comment]
The suggested code! 

Many Thanks.

**Comment by ambishaw** [comment]
@prathyusha12345 Thank you very much! This was very helpful.
