### ISSUE TITLE
Cant run project on VS 2015

### ISSUE THREAD

**Issue by JyotsnaRamanan** [dotnet/machinelearning-samples#330]
Problem encountered on https://dotnet.microsoft.com/learn/machinelearning-ai/ml-dotnet-get-started-tutorial/dataset
Operating System: Windows 10

Provide details about the problem you are experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.

After downloading the sample Iris data, I tried opening the solution in vs 2015, but not able to do so. 

![error](https://user-images.githubusercontent.com/12887731/55019831-a1022480-4fc3-11e9-829b-1070131f1690.PNG)

**Comment by prathyusha12345** [comment]
@JyotsnaRamanan  Visual Studio 2017 is recommended for ML.Net. As you are using Vs2015, Make sure you have installed below
  

1. The latest NuGet VSIX for VS 2015 (v3.6.0 as of this writing) from https://www.nuget.org/downloads
   

2.  The .NET Standard Build Support extension from https://aka.ms/netstandard-build-support-netfx
   

And  assuming you are using .NET Framework, since you are on VS 2015, you will also need to change your project's **platform target** from `Any CPU` to **x64**

Please find more details about this issue [here](https://github.com/dotnet/machinelearning/issues/717#issuecomment-419935031) 

Please let me know if you still face any issue.

**Comment by prathyusha12345** [comment]
Assuming the issue solved. Closing the issue. Please reopen if you encounter issue again. thanks
