### ISSUE TITLE
[Discussion] Profusion of subfolders and approaches for samples structure

### ISSUE THREAD

**Issue by awf** [dotnet/machinelearning-samples#34]
https://github.com/dotnet/machinelearning-samples/tree/master/samples
has three subfolders, each with few examples.

Sorting of the folders is alphabetical, not in order of difficutly.

Suggestion:  Flatten this hierarchy as follows.  

101_BinaryClassification_SentimentAnalysis 
102_Clustering_Iris
103_MulticlassClassification_Iris 
201_Regression_TaxiFarePrediction
202_BinaryClasification_Titanic 
203_Regression_BikeSharingDemands 
301_eShopDashboardML 
302_GitHubLabeler

**Comment by CESARDELATORRE** [comment]
@awf - The number of samples will grow significantly in the future and we want to segregate them by type.
The end-to-end apps are not at the same level of complexity than the getting started samples.
I know that with your suggested prefix that could be addressed but since we're thinking about having tens of samples targeting multiple industries and all the ML Tasks, etc. I think t iis better if we clearly segregate the samples in several folders.
Also, level 100, 200, 300 might be clear for some folks but not for others. If we explicitly say it in the folder, it might be clearer.
In any case, thanks for the idea (mark the samples with 100, 200, 300), I'll take it into account when evolving the samples, could be in the folder or in the README, etc.


In the long term, we'll probably segregate/mark the samples based on two pivots:
- ML Tasks (Regression, Binary-Classification, Multi-class classification, Clustering, etc.)
- Industry (Finance, Retail, Engineering, etc.)

Although the classification/pivots could also be in the main README as a matrix, too. It doesn't mean we'll create a bunch of folders, neither.

Another addition that will increase the folders are the potential additional samples on languages like F# and VB.NET, etc...

Feel free to keep discussing on this thread while we update the samples. 👍

**Comment by CESARDELATORRE** [comment]
Closing this issue as it is stale. 
The folders are:
- Getting Started samples
- End-to-end samples
As explained in the home page or README.MD at the beginning of the table:
https://github.com/dotnet/machinelearning-samples#mlnet-samples

Which maps with the folders here:
https://github.com/dotnet/machinelearning-samples/tree/master/samples/csharp
