### ISSUE TITLE
Question regarding MNIST example

### ISSUE THREAD

**Issue by jeffprosise** [dotnet/machinelearning-samples#368]
The MNIST example works. But how do you correlate the probabilities in the Score array in the output to the labels? If I pass the pattern for a 4 to Predict(), it is the element at index 2 in the Score array that shows the highest probability.

**Comment by kevmal** [comment]
The example maps the actual number to a key by `mlContext.Transforms.Conversion.MapValueToKey("Label", "Number")`, the default here is to assign keys to values by occurrence. So in this case 4 corresponds to index 2 because two distinct values appear in the data before the first 4.  To get a more intuitive ordering the optional parameter `keyOrdinality` can be set to specify `ByValue` ordering.

**Comment by prathyusha12345** [comment]
Fixed this. so closing the issue. Please reopen if you still have any issues.
