### ISSUE TITLE
Deep Reinforcement Learning Examples

### ISSUE THREAD

**Issue by Solange-Cerny** [dotnet/machinelearning-samples#372]
Hello, 

Could we please have  some examples of  DQN e.g. atari etc. as it is most focused topic in AI at the moment.

Thank you,
Roman

**Comment by CESARDELATORRE** [comment]
ML.NET currently doesn't support Reinforcement Learning, hence we cannot create samples about it.
We're planning however on that feature for future releases for ML.NET.
IF you have specific scenarios where you need it, please, create an issue at the ML.NET repo requesting 'Reinforcement Learning' as a feature for the backlog while explaining the scenarios you would like it for, ok?
Create issue here: https://github.com/dotnet/machinelearning/issues

I'm closing this issue here since it currently doesn't apply to the samples.
Thanks for your feedback! 👍
