### ISSUE TITLE
System.ArgumentOutOfRangeException

### ISSUE THREAD

**Issue by tomatoe45** [dotnet/machinelearning-samples#412]
Problem encountered on https://dotnet.microsoft.com/learn/machinelearning-ai/ml-dotnet-get-started-tutorial/code
Operating System: Windows

From Petals Training

System.ArgumentOutOfRangeException: 'Must be at least 2.
Parameter name: numClasses'

var model = pipeline.Fit(trainingDataView);

**Comment by prathyusha12345** [comment]
which version of ML.Net are you using?Are you using 1.0.0-preview as per the link  https://dotnet.microsoft.com/learn/machinelearning-ai/ml-dotnet-get-started-tutorial/code?  I just now followed the steps in tutorial to see any error but the code is running successfully.

Please confirm the above so that we can look for more details if you face the same issue.

**Comment by tomatoe45** [comment]
Thanks.. i'll try to create another sample..
