### ISSUE TITLE
Community guidelines for refactoring samples to VB.Net?

### ISSUE THREAD

**Issue by danucalovj** [dotnet/machinelearning-samples#430]
Hello,

I read this:

https://github.com/dotnet/machinelearning-samples/blob/master/CONTRIBUTING.md

But wanted to specifically ask whether or not I can contribute to this repo by refactoring existing samples into VB.Net samples for the VB.Net community.

**Comment by prathyusha12345** [comment]
I agree.That's nice job!!! Its better to send us a link to the samples in your repo intead of one link per sample. @CESARDELATORRE  can you please provide your opinion.

**Comment by CESARDELATORRE** [comment]
@danucalovj (adding Nukepayload2)- Thanks a lot for your interest on collaboration with ML.NET and VB.
So, there's currently a third-party effort working on migrating the ML.NET samples to VB. 
We won't be hosting/maintaining it, but it is owned by a third party.
You can see the link at the ML.NET Community samples page:
https://github.com/dotnet/machinelearning-samples/blob/master/docs/COMMUNITY-SAMPLES.md

In concrete, here:
https://github.com/Nukepayload2/machinelearning-samples/tree/master/samples/visualbasic

It would be great if you can collaborate with @Nukepayload2 and join forces for that VB effort?
If you'd like, for the future, you could even create your own GuitHub organization such as MLNET-VB or similar instead of using a personal repo.

From the ML.NET product group we'd like to point to a single place for ML.NET VB samples so contributions to it help a lot more. :)

Thoughts?

**Comment by danucalovj** [comment]
Ok cool sounds good, I'll go ahead and see if I can contact Nukepayload2 and go from there. I'll keep you all posted on that effort. Thanks.
