### ISSUE TITLE
How to pass a Stream of Images in  Object Detection End-to-End

### ISSUE THREAD

**Issue by usmankaiiz** [dotnet/machinelearning-samples#445]
Currently, ML.NET is focusing on the images stored on folders, what if I want to use the model with a camera, in a real-time scenario. there is no documentation for how to pass the Stream of Images.

**Comment by danucalovj** [comment]
@usmankaiiz that's usually the case with any ML framework, with the goal of the framework being to train, then do inference against a trained model. Don't think we can expect the ML.Net team to provide examples for every use case.

However, with that said, if you share your code a few folks in the community here or on Stack Overflow might help completing your code.

One you've got your model built, I don't see why you can't just pass the bytes from your capture stream into the model for prediction... Instead of reading a file and passing each image from a folder, just pass the bytes from your stream.

**Comment by SuperDaveOsbourne** [comment]
C# 8 and .NET Core 3: Async Streams https://www.youtube.com/watch?v=Dg3p_pOXUJs

**Comment by CESARDELATORRE** [comment]
@usmankaiiz is right, we still don't have clear samples using in-memory images either coming from HTTP or from streaming such as a laptop camera. This is a specially important case when you want to run the model in certain scenarios (not so critical for training the model).

See the following issues at the ML.NET repo and **provide your additional feedback in those issues or new issues created at the ML.NET repo**, since the ML.NET API for TensorFlow and ONNX models might also need to be improved about this point:

https://github.com/dotnet/machinelearning/issues/3369

Check this info for additional related TF samples:
https://docs.microsoft.com/en-us/dotnet/api/microsoft.ml.transforms.tensorflowmodel.scoretensorflowmodel?view=ml-dotnet-preview

https://github.com/dotnet/machinelearning/issues/2121

**Comment by usmankaiiz** [comment]
@CESARDELATORRE I guess there is an update on 1.1 which includes streaming pictures for model prediction

**Comment by prathyusha12345** [comment]
@usmankaiiz  Yes we have upgraded the sample to 1.1 to load the images from in-memory in the sample here https://github.com/dotnet/machinelearning-samples/tree/master/samples/csharp/end-to-end-apps/DeepLearning_ObjectDetection_Onnx

**Comment by nfnpmc** [comment]
In machinelearning-samples/samples/csharp/end-to-end-apps/DeepLearning_ObjectDetection_Onn
There IS a class ImageInputData.
but the IDataView is made from ImageNetData,
var dataView = _mlContext.Data.LoadFromEnumerable(new List<ImageNetData>());
where did that come from?
When I use my class
    public class DataBlob
    {
        [LoadColumn(0)]
        [ImageType(720, 576)]
        public Bitmap Image { get; set; }

        [LoadColumn(1)]
        public string Label { get; set; }
        ... etc.
I get 
System.ArgumentOutOfRangeException: 'Could not determine an IDataView type for member Image
Parameter name: rawType'

**Comment by colbylwilliams** [comment]
@usmankaiiz we're adding streaming input to the E2E Onnx sample [here](https://github.com/dotnet/machinelearning-samples/pull/602)
