### ISSUE TITLE
Cannot execute tensorflow scoring samples

### ISSUE THREAD

**Issue by mrcabellom** [dotnet/machinelearning-samples#53]
I have a problem triying to execute tensorflow scoring inception sample. It throws an exception: cannot instantiate transform.ImageLoader

**Comment by sfilipi** [comment]
Did you update to the latest ml.net nuget? Due to some recent changes, the assembly containing ImageLoader needs to be loaded before executing the rest of the code. 

As a workaround, to cause that assembly to load,  you can try adding the following

 if (typeof(ImageLoaderTransform) == null) throw new Exception("ImageAnalytics not loaded correctly");

to [Program.cs, line 25] (https://github.com/dotnet/machinelearning-samples/blob/master/samples/csharp/examples/DeepLearning_TensorFlowMLNETInceptionv3ModelScoring/Program.cs)


and add the following using:
using Microsoft.ML.Runtime.ImageAnalytics;

**Comment by mrcabellom** [comment]
My ml.net nuget packages were updated to 0.6.0. The problem was (as you have said) the assembly. I have added the workaround and is working, but it is also necessary to include using Microsoft.ML.Transforms because the program needs the Tensorflow scoring assembly too.

I have added:

if (typeof(TensorFlowTransform) == null) throw new Exception("Tensorflow not loaded correctly");

and the using Microsoft.ML.Transforms

Thank you so much!

I hope you can solve the assembly loads dependency.

**Comment by sfilipi** [comment]
Thanks for describing the full solution. 
The new API should not have those kinds of problems. 

cc @CESARDELATORRE

**Comment by sfilipi** [comment]
@mrcabellom you can submit a PR towards this repo, with your fix, if you want to share it.

**Comment by mrcabellom** [comment]
Done!

**Comment by CESARDELATORRE** [comment]
Closing this issue since it is stale. We have now two TF samples working on the latest ML.NET version (v0.7)
