### ISSUE TITLE
Unable to infer column types of the file provided

### ISSUE THREAD

**Issue by LetterFirst** [dotnet/machinelearning-samples#583]
System information

Windows 10 / Visual Studio Professinal 2017 15.9.14
.NET Version: .NET Core 2.1

Issue

I would like to thank all of you for your excellent work

What did you do? I'm trying to load a csv file from my desktop to ML Model Builder
What happened? An error appears (snapshot attached)
What did you expect? I loaded the csv file correctly from RStudio (snapshot attached)

![0](https://user-images.githubusercontent.com/53216682/61706404-519cec80-ad48-11e9-9859-74e5d465827f.PNG)
![1](https://user-images.githubusercontent.com/53216682/61706406-519cec80-ad48-11e9-870e-39ecbd51bc87.PNG)

**Comment by bamurtaugh** [comment]
Hi @LetterFirst - thank you for your feedback! It appears this issue relates to Model Builder rather than the ML.NET samples. In that case, your issue would be better-suited for the Model Builder repo: https://github.com/dotnet/machinelearning-modelbuilder/issues. Let us know if you have any questions about the ML.NET samples repo specifically 😊

**Comment by LetterFirst** [comment]
I apologize for my mistake. I'm going to write my query in the correct section. Thank you very much!
