### ISSUE TITLE
The project OnnxObjectDetectionApp does not load in VS

### ISSUE THREAD

**Issue by ddobric** [dotnet/machinelearning-samples#630]
Hi all,

for some reason the solution does not load OnnxObjectDetectionApp project.

![image](https://user-images.githubusercontent.com/1756871/64094430-ff45e700-cd5b-11e9-97b3-5f1cd45f5d2c.png)

The error:
> error  : Project file is incomplete. Expected imports are missing.

Using VS2019.

**Comment by colbylwilliams** [comment]
@ddobric WPF was added to .NET Core 3.0 which is still in preview, so that app depends on a preview version of .NET Core.  Can you confirm you've enabled .NET Core preview as described [here](https://github.com/dotnet/machinelearning-samples/tree/master/samples/csharp/end-to-end-apps/ObjectDetection-Onnx#solution)?

**Comment by ddobric** [comment]
Thanks for feedback.
The reason for this issue was a temporary **slow** internet connection. It seems to be rather a VS issue. After establishing of the "fast" internet connection, solution loads correctly.

Damir
