### ISSUE TITLE
Is it possible to use an exported onnx file from Azure Custom Vison with this example?

### ISSUE THREAD

**Issue by andrecarlucci** [dotnet/machinelearning-samples#662]
I created a custom model on www.customvision.ai and would like to use the exported file with ml.net.
I tried just replacing the model file and the labels, but it didn't work.
Any direction you could point me to?

Tks!

**Comment by CESARDELATORRE** [comment]
I am guessing it is an Image Classifier, not an Object Detection Model since you just mentioned labels but not bounding boxes, right?

In any case, you need to provide a few parameters in the exact way your model needs, like image size, etc.
For that, you can open the ONNX model (Or TensorFlow model if exported as TensorFlow) with 'Netron tool' and check thigs like the image size you need to re-size, etc.

Please, take a look to this Blog Post where I'm doing the same thing you want to do (but in this case it is a TensorFlow model):

https://devblogs.microsoft.com/cesardelatorre/run-with-ml-net-c-code-a-tensorflow-model-exported-from-azure-cognitive-services-custom-vision/

You can see how to run an ONNX model here, although that one is Object Detection instead of Image Classification:

https://github.com/dotnet/machinelearning-samples/tree/master/samples/csharp/getting-started/DeepLearning_ObjectDetection_Onnx

**Comment by andrecarlucci** [comment]
Thanks, I'll take a look at these :)

One part that I didn't get it:

I'm actually using Object Detection.
Why do I need bounding boxes if the Object Detection model is already trained? 
When I export the onnx, I get the *model.onnx* and a label.txt files.

**Comment by luisquintanilla** [comment]
@andrecarlucci with object detection you're doing two things

1. Find the location where objects are in an image
2. Classify the objects found.

You need the bounding boxes for the first step. The bounding boxes provide the location in an image where objects were found. 

Closing this issue for now. Please feel free to open another issue if you run into additional issues.
