### ISSUE TITLE
Model Training on local machine

### ISSUE THREAD

**Issue by AlpeshValvi123** [dotnet/machinelearning-samples#699]
Is it necessary to train the model every time while the app is running on the local machine? Because it's much time to Training data. How can we improve that?

**Comment by CESARDELATORRE** [comment]
Not sure I understand. In order to make predictions, simply run a model, you just need to load the trained/serialized/saved model (.ZIP file), create the prediction engine and call .Predict(). 
Three lines of code to run in an end-user app. 
Training happens only in your 'back-storage' application when you get new data, etc.

Is that what you mean?

**Comment by luisquintanilla** [comment]
Closing this issue since a response was provided and there's no additional activity since then.
