### ISSUE TITLE
How to use Ensemble learners in ML.NET

### ISSUE THREAD

**Issue by bhrnjica** [dotnet/machinelearning-samples#701]
As I can see Ensemble learners were added into ML.NET in 0.3 version but I cannot find any example. Can someone point me to some of the examples of using multiple learners within one model?
Thank you in advance.

**Comment by CESARDELATORRE** [comment]
@bhrnjica - Ensembles are not in the ML.NET public API yet. They were made internal before the release of ML.NET 1.0.
We have it in our backlog to have it in the public API for ensembles, but we haven’t gotten to it yet because it was lower priority compared to other features.

Please, could you explain your business scenario and why you were initially thinking on using ensembles so we take it into account for our priorities in ML.NET?

**Comment by bhrnjica** [comment]
I have no special scenarios to use Ensembles. Anyhow when you have no good model with existing algorithms, last hope could be by using Ensembles.
