### ISSUE TITLE
Load a Pb or ONNX custom Pre-trained model

### ISSUE THREAD

**Issue by mranjbaran** [dotnet/machinelearning-samples#751]
Is it possible to load a custom Pb or ONNX model with ml.net like what we can do with ML.NET model (.zip file) format? 

Like this: _ITransformer trainedModel = mlContext.Model.Load("model.zip", out modelSchema);_

The model is **not created on customvision.ai** and is **not one of your ready-to-use pre-trained models**.

**Comment by CESARDELATORRE** [comment]
You can load an ONNX or TensorFlow model in ML.NET and use it (score, inference with it).
But it is not as simple as when loading an ML.NET .zip file model since you need to provide additional parameters needed by the DNN.

**See an TensorFlow examples here:**
https://github.com/dotnet/machinelearning-samples/tree/master/samples/csharp/getting-started/DeepLearning_ImageClassification_TensorFlow

https://github.com/dotnet/machinelearning-samples/tree/master/samples/csharp/end-to-end-apps/DeepLearning_ImageClassification_TensorFlow

**See an ONNX example here:**
https://github.com/dotnet/machinelearning-samples/tree/master/samples/csharp/end-to-end-apps/ObjectDetection-Onnx

**Comment by frank-dong-ms** [comment]
Cesar has already give out the sample, close the issue now.

**Comment by mranjbaran** [comment]
Thank Cesar for the explanations, as you mentioned it is not easy to implement this TF model and apart from the examples you mentioned, I could not find any other examples that I could learn better.

**Comment by ClementeGao** [comment]
hi can ml.net train othet model?
