### ISSUE TITLE
"Features" used instead of "PCAFeatures" for KMeans CustomerSegmentation sample

### ISSUE THREAD

**Issue by Vijay27anand** [dotnet/machinelearning-samples#771]
In the samples source file samples/csharp/getting-started/Clustering_CustomerSegmentation/CustomerSegmentation.Train/Program.cs

The PCAFeatures is the output in ProjectToPrincipalComponents, but "PCAFeatures"  is not used mlContext.Clustering.Trainers.KMeans featureColumnName, instead "Features" is used. Please let me know if this has to be fixed in the code or this is correct. 

              //STEP 2: Configure data transformations in pipeline 
                
       var dataProcessPipeline = 
       mlContext.Transforms.ProjectToPrincipalComponents(outputColumnName: "**PCAFeatures**", 
       inputColumnName: "Features", rank: 2)           
       .Append(mlContext.Transforms.Categorical.OneHotEncoding(outputColumnName: 
        "LastNameKey", inputColumnName: nameof(PivotData.LastName), 
        OneHotEncodingEstimator.OutputKind.Indicator));
 

              // (Optional) Peek data in training DataView after applying the ProcessPipeline's transformations
        Common.ConsoleHelper.PeekDataViewInConsole(mlContext, pivotDataView, dataProcessPipeline, 10);
        Common.ConsoleHelper.PeekVectorColumnDataInConsole(mlContext, "Features", pivotDataView, dataProcessPipeline, 10);

                //STEP 3: Create the training pipeline
        var trainer = mlContext.Clustering.Trainers.KMeans(featureColumnName: "**Features**", numberOfClusters: 3);

**Comment by Vijay27anand** [comment]
@CESARDELATORRE any update on this issue

**Comment by antoniovs1029** [comment]
Hi @Vijay27anand I didn't realize you had already opened this issue here, before duplicating it in the ML.NET main repository.

So I had moved the issue you created there into this repository in here:
https://github.com/dotnet/machinelearning-samples/issues/777

And there I have answered you that I don't think there's anything to be fixed. I give my reasons why there.

I will also close this since it can be considered a duplicate. If you need further discussions about this, please continue the discussion on issue #777 . Thanks!
