### ISSUE TITLE
"Features" used instead of "PCAFeatures" for KMeans CustomerSegmentation sample

### ISSUE THREAD

**Issue by Vijay27anand** [dotnet/machinelearning-samples#777]
### System information

In the samples source file

https://github.com/dotnet/machinelearning-samples/tree/master/samples/csharp/getting-started/Clustering_CustomerSegmentation/CustomerSegmentation.Train/Program.cs

### Issue

The PCAFeatures is the output in ProjectToPrincipalComponents, but "PCAFeatures" is not used mlContext.Clustering.Trainers.KMeans featureColumnName, instead "Features" is used. Please let me know if this has to be fixed in the code or this is correct.

### Source code / logs
```C#
//STEP 2: Configure data transformations in pipeline
var dataProcessPipeline = 
   mlContext.Transforms.ProjectToPrincipalComponents(outputColumnName: "**PCAFeatures**", 
   inputColumnName: "Features", rank: 2)           
   .Append(mlContext.Transforms.Categorical.OneHotEncoding(outputColumnName: 
       "LastNameKey", inputColumnName: nameof(PivotData.LastName), 
       OneHotEncodingEstimator.OutputKind.Indicator));

// (Optional) Peek data in training DataView after applying the ProcessPipeline's transformations
    Common.ConsoleHelper.PeekDataViewInConsole(mlContext, pivotDataView, dataProcessPipeline, 10);
    Common.ConsoleHelper.PeekVectorColumnDataInConsole(mlContext, "Features", pivotDataView, dataProcessPipeline, 10);

//STEP 3: Create the training pipeline
    var trainer = mlContext.Clustering.Trainers.KMeans(featureColumnName: "**Features**", numberOfClusters: 3);
```

**Comment by antoniovs1029** [comment]
So, I believe there's nothing to be fixed.

As explained in the [README of this sample](https://github.com/dotnet/machinelearning-samples/tree/master/samples/csharp/getting-started/Clustering_CustomerSegmentation), PCA is only used in order to visualize the clusters, but not to actually find the clusters. Because of this, it is okay for the KMeans trainer to use the whole original `Features `column instead of the `PCAFeatures` one.

If you then look into the `ClusteringPrediction` class, you can see that the PCAFeatures column is used to find the location that the datapoint will have on the plot:

https://github.com/dotnet/machinelearning-samples/blob/c4c2632135757110658ad2b502f6d18e8cd7f221/samples/csharp/getting-started/Clustering_CustomerSegmentation/CustomerSegmentation.Train/DataStructures/ClusteringPrediction.cs#L12-L13

This location is then used in the demo app to create the plot of the predictions.

So I will close this issue, but if you still have further comments on this, please feel free to reopen it. Thanks.
