### ISSUE TITLE
Hi Please tell me about the description of the dataset of Product.stats.csv of eShopDashboard Machine Learning Project of Sales Forecasting  like

### ISSUE THREAD

**Issue by Aamirkhan10218** [dotnet/machinelearning-samples#818]
Hi Please tell me about the description of the dataset of Product.stats.csv of eShopDashboard Machine Learning Project of Sales Forecasting  like 
what is the meaning of 
next
avg
count
max
min
prev
[products.stats.xlsx](https://github.com/dotnet/machinelearning-samples/files/4628273/products.stats.xlsx)
i'll be very grateful to you

_Originally posted by @Aamirkhan10218 in https://github.com/dotnet/machinelearning-samples/pull/661#issuecomment-628601541_

**Comment by luisquintanilla** [comment]
So the data is autogenerated. See step 3 to generate your own.

https://github.com/dotnet/machinelearning-samples/blob/master/samples/csharp/end-to-end-apps/Forecasting-Sales/docs/Create-and-train-the-models-%5BOptional%5D.md

The data starts at 2015 because the data that generates `product.stasts.xlsx` is loosely based on `Online Retail.xlsx`. Things like product names and a few other things are sourced from the original dataset. However, a lot of it is generated as well. `product.stats.xlsx` is just an aggregation from the data that's seeded into the DB. 

This is the endpoint that generates the data. https://github.com/dotnet/machinelearning-samples/blob/8697bec3e9c78beb2c3c4d3f915551c85bcdcb39/samples/csharp/end-to-end-apps/Forecasting-Sales/src/eShopDashboard/Controllers/OrderingController.cs#L44

This is the data that's seeded in the DB. https://github.com/dotnet/machinelearning-samples/tree/master/samples/csharp/end-to-end-apps/Forecasting-Sales/src/eShopDashboard/Infrastructure/Setup/DataFiles
