### ISSUE TITLE
Make OnnxObjectDetection Sample Compatible with Compact S1 Domain

### ISSUE THREAD

**Issue by T3rr0rByte13** [dotnet/machinelearning-samples#913]
Hi,
I have tried using the Compact Domain for object detection, and I am only getting about 52% precision. However when I train the model with the Compact S1 Domain I'm getting 92% precision. However I can only use the Compact Domain for use in the sample. Is there anyway to modify the sample to get it to use the Compact S1 Domain?

**Comment by luisquintanilla** [comment]
@T3rr0rByte13 the Cognitive Services Custom Vision service in many cases allows models to be export as an ONNX model that can be used with ML.NET. ML.NET however does not have control over the output from Custom Vision since it's a different product / service. You can use something like Netron to inspect the model you get from Custom Vision and get a sense of what your model inputs and outputs are. 

Currently there are no plans at the moment to add a sample to this repo for that scenario. However, you can take a look at this sample from a workshop which details how to use Compact S1 models.

https://mlnet-workshop.azurewebsites.net/posts/11.2-inspect-model
